### ISSUE TITLE
3.0.0 Error on connecting to systemd socket (on ubuntu 20.04.6)

### ISSUE THREAD

**Issue by ngmip** [jpmsilva/jsystemd#10]
Hello,

I am trying to use the version 3.0.0 of jsystemd-spring-boot-starter with springboot 3.0.6 on a ubuntu 20.04.6. But I get an error.

On startup I see the following error message :
```
[WARN ] 2023-07-13 10:39:34,140 [main] c.g.j.j.SystemdNotify - Could not connect to systemd socket
java.net.SocketException: Protocol wrong type for socket
    at sun.nio.ch.UnixDomainSockets.connect0(Native Method) ~[?:?]
    at sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:148) ~[?:?]
    at sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:144) ~[?:?]
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:851) ~[?:?]
    at com.github.jpmsilva.jsystemd.SystemdNotify.createSocketChannel(SystemdNotify.java:57) ~[classes/:?]
    at com.github.jpmsilva.jsystemd.SystemdNotify.<clinit>(SystemdNotify.java:45) ~[classes/:?]
    at com.github.jpmsilva.jsystemd.SystemdUtilities.isUnderSystemd(SystemdUtilities.java:76) ~[classes/:?]
    at com.github.jpmsilva.jsystemd.SystemdSpringApplicationRunListener.createSystemd(SystemdSpringApplicationRunListener.java:67) ~[jsystemd-spring-boot-starter-3.0.0.jar:?]
    at com.github.jpmsilva.jsystemd.SystemdSpringApplicationRunListener.<init>(SystemdSpringApplicationRunListener.java:46) ~[jsystemd-spring-boot-starter-3.0.0.jar:?]
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
    at org.springframework.core.io.support.SpringFactoriesLoader$FactoryInstantiator.instantiate(SpringFactoriesLoader.java:382) ~[spring-core-6.0.8.jar:6.0.8]
    at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactJulory(SpringFactoriesLoader.java:228) ~[spring-core-6.0.8.jar:6.0.8]
    at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:206) ~[spring-core-6.0.8.jar:6.0.8]
    at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:160) ~[spring-core-6.0.8.jar:6.0.8]
    at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:461) ~[spring-boot-3.0.6.jar:3.0.6]
    at org.springframework.boot.SpringApplication.getRunListeners(SpringApplication.java:445) ~[spring-boot-3.0.6.jar:3.0.6]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) ~[spring-boot-3.0.6.jar:3.0.6]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.6.jar:3.0.6]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.6.jar:3.0.6]
```

The .service files goes as follow :
```
[Unit]
Description=my-springboot3-service Spring Boot Application

[Service]
#Type=simple
Type=notify
User=my-springboot3-service
Environment="LOADER_HOME=/opt/my-springboot3-service"
Environment="LOADER_SYSTEM=true"
WorkingDirectory=/srv/my-springboot3-service
ExecStart=/usr/bin/java [irrelevant JVM args removed fo brevity] org.springframework.boot.loader.PropertiesLauncher --debug
SuccessExitStatus=143
TimeoutStopSec=10
#Restart=on-failure
Restart=no
Restart=no
RestartSec=5
LimitNOFILE=65535
TimeoutStartSec=90

[Install]
WantedBy=multi-user.target
```

I use to have springboot > 2.4.x service working fine with jsystemd 2.0.1 on the same OS (Ubuntu 20.04.6) with the same .service file but that's the first time I try to work with springboot 3 and jsystemd 3.0.0.

I am not remotely familiar with systemd socket yet I'am currently trying to debug the thing.
I'll keep the issue updated with what I find but if in the mean time anyone has an idea he's most welcome :-D

The java version used is OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu120.04, mixed mode, sharing)

P.S. don't mind the line numbers in the stack-trace, I added a few log-lines to help me in my debugging process.

**Comment by ngmip** [comment]
After one full day spent grinding I could not make it work. :'(

The error happens when the condition (`@ConditionalOnSystemd`) is evaluated for the autoconfiguration class.
This condition calls the `SystemdNotify#createSocketChannel` and that where the the exception is raised.

The socket it tries to connect to is '/run/systemd/notify'. This file exists, it's owned by 'root' user with '777' permissions.

I tried to change the user of my service to use 'root'
I tried to use the same .service file than the one documented in the [3.0.0/how to](https://jpmsilva.github.io/jsystemd-site/versions/3.0.0/howto.html)
I could not find any "type of protocol" information related to systemd notify socket.

In short, I'm stuck T_T

**Comment by jpmsilva** [comment]
Hi Nicolas

I just wanted to let you know that I am actively researching this.
For the moment it appears I might have to rollback on the decision to ship 3.0 without JNA, seeing as there appears to be an issue with the support for datagram channels in conjunction with Unix domain sockets in Java.
I can confirm that the issue you reported is reproducible under the conditions you mention, and I’ll try to fix it ASAP.

Thank you for the report

**Comment by jpmsilva** [comment]
Hi @ngmip 
Care to test with newly minted 3.1.0?
I tested under the exact conditions you mentioned (Ubuntu 20.04.6) and it worked correctly.
Thank you for the report

**Comment by ngmip** [comment]
@jpmsilva works like a charm !

many thanks
